# Generated by Django 5.2.11 on 2026-02-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_group_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='dre_section',
            field=models.CharField(choices=[('RECEITA_OPERACIONAL', 'Receita Operacional'), ('CUSTOS_DIRETOS', 'Custos Diretos (Serviços)'), ('DESPESAS_ADMIN', 'Despesas Administrativas'), ('DESPESAS_COMERCIAIS', 'Despesas Comerciais'), ('DESPESAS_OPERACIONAIS', 'Despesas Operacionais'), ('DESPESAS_FINANCEIRAS', 'Despesas Financeiras'), ('IMPOSTOS', 'Impostos/Tributos'), ('OUTRAS', 'Outras')], default='RECEITA_OPERACIONAL', max_length=40),
        ),
    ]
